"""add_flow_subscriptions_table_v2

Revision ID: 35267383f277
Revises: a27127f781e2
Create Date: 2025-11-04 09:46:46.135175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35267383f277'
down_revision: Union[str, None] = 'a27127f781e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flow_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('min_score', sa.Numeric(precision=3, scale=2), server_default='0.75', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ticker_id', name='uq_flow_subscription_user_ticker')
    )
    op.create_index('ix_flow_subscriptions_ticker_active', 'flow_subscriptions', ['ticker_id', 'is_active'], unique=False)
    op.create_index('ix_flow_subscriptions_user', 'flow_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_flow_subscriptions_user', table_name='flow_subscriptions')
    op.drop_index('ix_flow_subscriptions_ticker_active', table_name='flow_subscriptions')
    op.drop_table('flow_subscriptions')
    # ### end Alembic commands ###
