"""add_option_flow_table

Revision ID: 41ac9f7d08b8
Revises: 6707212a00d9
Create Date: 2025-10-25 12:34:22.524318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ac9f7d08b8'
down_revision: Union[str, None] = '6707212a00d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('option_flow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('contract_symbol', sa.String(length=32), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('strike', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiration', sa.Date(), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('volume_oi_ratio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('premium', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('flags', sa.String(length=256), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_option_flow_anomaly_score', 'option_flow', ['anomaly_score'], unique=False)
    op.create_index('ix_option_flow_contract_detected', 'option_flow', ['contract_symbol', 'detected_at'], unique=False)
    op.create_index(op.f('ix_option_flow_contract_symbol'), 'option_flow', ['contract_symbol'], unique=False)
    op.create_index('ix_option_flow_ticker_detected', 'option_flow', ['ticker_id', 'detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_option_flow_ticker_detected', table_name='option_flow')
    op.drop_index(op.f('ix_option_flow_contract_symbol'), table_name='option_flow')
    op.drop_index('ix_option_flow_contract_detected', table_name='option_flow')
    op.drop_index('ix_option_flow_anomaly_score', table_name='option_flow')
    op.drop_table('option_flow')
    # ### end Alembic commands ###
