"""add_news_articles_table

Revision ID: 6707212a00d9
Revises: f3f6f2d64d2c
Create Date: 2025-10-23 19:38:11.851604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6707212a00d9'
down_revision: Union[str, None] = 'f3f6f2d64d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='newssentimentlabel', native_enum=False, length=16), nullable=True),
    sa.Column('sentiment_compound', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_news_articles_ticker_published', 'news_articles', ['ticker_id', 'published_at'], unique=False)
    op.create_index('ix_news_articles_url', 'news_articles', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_articles_url', table_name='news_articles')
    op.drop_index('ix_news_articles_ticker_published', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
