"""add_flow_subscriptions_table

Revision ID: a27127f781e2
Revises: 41ac9f7d08b8
Create Date: 2025-11-04 09:45:07.340271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27127f781e2'
down_revision: Union[str, None] = '41ac9f7d08b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
